apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: collab-svc-workload
  namespace: default
spec:
  container:
    env:
    - key: DOCLET_COLLAB_ADDR
      value: :8090
    image: host.k3d.internal:10082/doclet-collab-svc-image:v1-e0458407
  dependencies:
    endpoints:
    - component: nats
      envBindings:
        address: DOCLET_NATS_URL
      name: tcp
      visibility: project
  endpoints:
    http:
      port: 8090
      type: HTTP
  owner:
    componentName: collab-svc
    projectName: doclet
