apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: document-svc-workload
  namespace: default
spec:
  container:
    env:
    - key: DOCLET_DOCUMENT_ADDR
      value: :8080
    - key: DB_PASSWORD
      value: "doclet"
    - key: DB_USER
      value: "doclet"
    image: host.k3d.internal:10082/doclet-document-svc-image:v1-4a2acc61
  endpoints:
    http:
      type: HTTP
      port: 8080
      visibility: [external]
  dependencies:
    endpoints:
      - component: postgres
        name: tcp
        visibility: project
        envBindings:
          address: DOCLET_DATABASE_URL
      - component: nats
        name: tcp
        visibility: project
        envBindings:
          address: DOCLET_NATS_URL
  owner:
    componentName: document-svc
    projectName: doclet
