apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: document-svc-workload
  namespace: default
spec:
  container:
    env:
    - key: DOCLET_DOCUMENT_ADDR
      value: :8080
    - key: DB_PASSWORD
      value: doclet
    - key: DB_USER
      value: doclet
    image: host.k3d.internal:10082/doclet-document-svc-image:v1-e0458407
  dependencies:
    endpoints:
    - component: postgres
      envBindings:
        address: DOCLET_DATABASE_URL
      name: tcp
      visibility: project
    - component: nats
      envBindings:
        address: DOCLET_NATS_URL
      name: tcp
      visibility: project
  endpoints:
    http:
      port: 8080
      type: HTTP
      visibility:
      - external
  owner:
    componentName: document-svc
    projectName: doclet
